---
title: "2020 forecasts"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)

library(leaflet)
library(leaflet.providers)
library(sf)
```

Forecasts for the risk of a successfull coup ("coup") as well as any coup attempt ("attempt"), including failed attempts, in 2020.  

The risk values shown are percentages that can theoretically range from 0% to 100%. These are created from the underlying raw probabilities, which can range from 0 to 1, and then rouned to 1 decimal point. 

```{r, include = TRUE}
World <- readRDS("_data/World.rds")

# x is the input probability, 0-1
format_prob <- function(x) {
  perc <- sprintf("%.1f%%", x)
  # Cases that round to 0.0
  perc[x < 0.05 & !is.na(x)] <- "<0.1%"
  perc[is.na(x)] <- "n/a"
  perc
}

labels = sprintf(
  "<strong>%s</strong><br/>Attempt: %s<br/>Coup: %s<br>Failed: %s",
  World$name, format_prob(World$attempt), format_prob(World$coup),
  format_prob(World$failed)
) %>% lapply(htmltools::HTML)

# I previously used colorQuantile for this, but this distorts how high the risk
# really is in some countries. Better to use explicit bins. 
pal_p <- colorBin("viridis", bins = c(0, 0.5, 1, 2, 5, Inf))

leaflet(width = "100%", height = "600px") %>%
  #addProviderTiles("Esri.WorldGrayCanvas", group = "Esri.WorldGrayCanvas") %>%
  addPolygons(data = World, weight = 1, color = "black", smoothFactor = 0.3,
              fillOpacity = 0.8, fillColor = ~pal_p(attempt),
              popup = labels,
              group = "Any Coup Attempt",
              highlight = highlightOptions(weight = 3)
              ) %>%
  # coup
  addPolygons(data = World, weight = 1, color = "black", smoothFactor = 0.3,
              fillOpacity = 0.8, fillColor = ~pal_p(coup),
              popup = labels,
              group = "Successful Coup",
              highlight = highlightOptions(weight = 3)
              ) %>%
  # failed attempt
  addPolygons(data = World, weight = 1, color = "black", smoothFactor = 0.3,
              fillOpacity = 0.8, fillColor = ~pal_p(failed),
              popup = labels,
              group = "Failed Attempt",
              highlight = highlightOptions(weight = 3)
              ) %>% 
  addLegend(pal = pal_p, values = World$coup, opacity = 0.8,
            labFormat = labelFormat(big.mark = "'"),
            title = "Statistical Risk (%)") %>%
  addLayersControl(
    baseGroups = c("Any Coup Attempt", "Successful Coup", "Failed Attempt"),
                   position = "topleft",
    options = layersControlOptions(collapsed = FALSE)
  ) %>%
  setView(lng = 0, lat = 20, zoom = 2)
```

