---
title: "Links to other public forecasting projects"
output: 
  html_document:
    includes:
      in_header: _links_header.html
---

There are several projects that produce public forecasts of different forms of political instability and violence:

## ViEWS 

Political Violence Early Warning System for Africa by the Uppsala University Department of Peace and Conflict Research. 

[www.pcr.uu.se/research/views/](https://www.pcr.uu.se/research/views/){target="_blank"}

## Early Warning Project 

One-year ahead forecasts for the risk of mass atrocities, including genocide, by the United States Holocaust Memorial Museum. 

[earlywarningproject.ushmm.org](https://earlywarningproject.ushmm.org){target="_blank"}

## Atrocities Forecasting Project

Five-year ahead forecasts (currently covering 2016-2020) for the onset of genocide or politicide campaigns. 

[politicsir.cass.anu.edu.au/research/projects/atrocity-forecasting](https://politicsir.cass.anu.edu.au/research/projects/atrocity-forecasting){target="_blank"}

## CoupCast

One-month and one-year ahead forecasts for the risk of coup attempts, using an approach that draws on the methods we developed for forecasting irregular leadership changes (which include coups; [Beger, Dorff, and Ward 2016](https://www.sciencedirect.com/science/article/abs/pii/S0169207015000485)). By OEF Research.

[oefresearch.org/activities/coup-cast](https://oefresearch.org/activities/coup-cast){target="_blank"}

## PART and the Democratic Space Barometer

The Predicting Adverse Regime Transitions and Democratic Space Barometer are two related projects we did with the V-Dem Institute at the University of Gothenburg. 

PART provides 2-year forecasts (currently covering 2019-2020) for the risk that a country will be more autocratic, using V-Dem's four-category regimes of the world index. 

The Democratic Spaces Barometer produces 2-year forecasts for the probability of substantial improvement or worsening on six different facets of democratic governance.

PART: [www.v-dem.net/en/analysis/Forecast/](https://www.v-dem.net/en/analysis/Forecast/){target="_blank"}

Democratic Spaces Barometer: [www.v-dem.net/en/analysis/DemSpace/](https://www.v-dem.net/en/analysis/DemSpace/){target="_blank"}

